### ISSUE TITLE
Add Support for File Listing/Searching

### ISSUE THREAD

**Issue by cbadke** [trickest/trickest-cli#117]
#### Description

The CLI `file` functionality supports `get`, `create`, `delete` but not `list`. This requires the user to either know exactly what files are in the account or reference the web app to see what files are available.

I would like to be able to list the files currently stored my account from the CLI. In the codebase, it appears that the [getMetadata](https://github.com/trickest/trickest-cli/blob/main/cmd/files/files.go#L42-L55) function may already expose the required API endpoint.

Ideal case would be to have two modes:

1. list all files in the account
2. list all files that match a search term

If case 1 is provided, users can work around case 2 with shell tools if needed.

For extra bonus points, allow a JSON output format that includes the upload time and file sizes (emulating the full output of the web app).

**Comment by mhmdiaa** [comment]
Implemented both modes in #119. Check out the PR description for usage examples.

Cheers!
