### ISSUE TITLE
The Windows builds are missing .exe in the filename

### ISSUE THREAD

**Issue by CyberLykan** [trickest/trickest-cli#62]
#### Problem description
The Windows builds are missing .exe in the filename.
#### Steps to reproduce
Unzip the zip file and look for a executable.
#### Expected behaviour
An executable named `trickest-cli-1.0.2-windows-XXX.exe` instead of a file named `trickest-cli-1.0.2-windows-XXX`.
#### Screenshots if applicable
![image](https://user-images.githubusercontent.com/21145060/174668821-9f91d7cd-c935-4cf1-b381-39c110844620.png)
#### Environment
Windows

**Comment by mhmdiaa** [comment]
Updated the [latest release](https://github.com/trickest/trickest-cli/releases/tag/v1.0.2). Thanks @CyberLykan!
